/-
Copyright (c) 2026 Rémy Degenne. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Rémy Degenne
-/
module

public import Wang2026Almost.LeanMachineLearning.Betting.Strategies
public import Mathlib.Probability.Independence.Basic
public import Mathlib.Probability.Process.Adapted

/-!
# The filtration of the past observations

For a process `X : ℕ → Ω → β`, `pastFiltration X hX n` is the σ-algebra generated by the first
`n` observations `X 0, …, X (n - 1)` (the strict past at time `n`). It is the filtration for which
the paper's *predictable plug-in* strategies are predictable: a plug-in strategy `lam`
(`IsPlugIn X lam`, `lam n` a measurable function of `X 0, …, X (n - 1)`) is adapted to it, and
`X n` is measurable for its `σ`-algebra at time `n + 1`. When the observations are independent,
`X n` is independent of the past filtration at time `n`: the observations are i.i.d. along the
past filtration in the sense used for the general (filtration) forms of the paper's results.

## Main definitions

* `pastFiltration X hX`: the filtration `n ↦ σ(X 0, …, X (n - 1))`.

## Main statements

* `measurable_pastFiltration_succ`: `X n` is `pastFiltration X hX (n + 1)`-measurable.
* `IsPlugIn.adapted_pastFiltration`: plug-in strategies are adapted to the past filtration.
* `indep_pastFiltration`: for independent observations, `X n` is independent of
  `pastFiltration X hX n`.
-/

@[expose] public section

open MeasureTheory ProbabilityTheory

namespace Learning.Betting

variable {Ω β : Type*} {mΩ : MeasurableSpace Ω} [mβ : MeasurableSpace β]

/-- The filtration of the past observations: at time `n`, the `σ`-algebra generated by
`X 0, …, X (n - 1)`. -/
def pastFiltration (X : ℕ → Ω → β) (hX : ∀ n, Measurable (X n)) : Filtration ℕ mΩ where
  seq n := MeasurableSpace.comap (fun ω (k : Fin n) ↦ X k ω) inferInstance
  mono' n n' h := by
    simp only
    rw [← measurable_iff_comap_le]
    have : (fun ω (k : Fin n) ↦ X k ω) =
        (fun x (k : Fin n) ↦ x (Fin.castLE h k)) ∘ (fun ω (k : Fin n') ↦ X k ω) := rfl
    rw [this]
    exact measurable_comp_comap _ (by fun_prop)
  le' n := by
    rw [← measurable_iff_comap_le]
    exact measurable_pi_iff.mpr fun k ↦ hX k

lemma pastFiltration_apply (X : ℕ → Ω → β) (hX : ∀ n, Measurable (X n)) (n : ℕ) :
    pastFiltration X hX n = MeasurableSpace.comap (fun ω (k : Fin n) ↦ X k ω) inferInstance :=
  rfl

/-- The vector of the first `n` observations is measurable for the past filtration at time
`n`. -/
lemma measurable_pastFiltration_vec (X : ℕ → Ω → β) (hX : ∀ n, Measurable (X n)) (n : ℕ) :
    Measurable[pastFiltration X hX n] (fun ω (k : Fin n) ↦ X k ω) :=
  measurable_iff_comap_le.mpr le_rfl

/-- The observation `X k` is measurable for the past filtration at every time `n > k`. -/
lemma measurable_pastFiltration_of_lt (X : ℕ → Ω → β) (hX : ∀ n, Measurable (X n)) {k n : ℕ}
    (hkn : k < n) : Measurable[pastFiltration X hX n] (X k) :=
  (measurable_pi_apply (⟨k, hkn⟩ : Fin n)).comp (measurable_pastFiltration_vec X hX n)

/-- The observation `X n` is measurable for the past filtration at time `n + 1`. -/
lemma measurable_pastFiltration_succ (X : ℕ → Ω → β) (hX : ∀ n, Measurable (X n)) (n : ℕ) :
    Measurable[pastFiltration X hX (n + 1)] (X n) :=
  measurable_pastFiltration_of_lt X hX n.lt_succ_self

/-- A plug-in strategy is adapted to the past filtration of the observations. -/
lemma IsPlugIn.adapted_pastFiltration {X lam : ℕ → Ω → ℝ} (hX : ∀ n, Measurable (X n))
    (h : IsPlugIn X lam) : Adapted (pastFiltration X hX) lam := by
  intro n
  obtain ⟨f, hf, hlam⟩ := h n
  have : lam n = f ∘ (fun ω (k : Fin n) ↦ X k ω) := funext hlam
  rw [this]
  exact hf.comp (measurable_pastFiltration_vec X hX n)

/-- For independent observations, `X n` is independent of the past observations
`X 0, …, X (n - 1)`. -/
lemma indep_pastFiltration {μ : Measure Ω} {X : ℕ → Ω → β} (hX : ∀ n, Measurable (X n))
    (hindep : iIndepFun X μ) (n : ℕ) :
    Indep (MeasurableSpace.comap (X n) mβ) (pastFiltration X hX n) μ := by
  have h := hindep.indepFun_finset {n} (Finset.range n) (by simp) hX
  rw [IndepFun_iff_Indep] at h
  refine indep_of_indep_of_le_right (indep_of_indep_of_le_left h ?_) ?_
  · rw [← measurable_iff_comap_le]
    have : X n = (fun x : ({n} : Finset ℕ) → β ↦ x ⟨n, Finset.mem_singleton_self n⟩) ∘
        (fun ω (i : ({n} : Finset ℕ)) ↦ X i ω) := rfl
    rw [this]
    exact measurable_comp_comap _ (by fun_prop)
  · rw [pastFiltration_apply, ← measurable_iff_comap_le]
    have : (fun ω (k : Fin n) ↦ X k ω) =
        (fun x : (Finset.range n) → β ↦ fun k : Fin n ↦ x ⟨k, Finset.mem_range.2 k.2⟩) ∘
        (fun ω (i : Finset.range n) ↦ X i ω) := rfl
    rw [this]
    exact measurable_comp_comap _ (by fun_prop)

end Learning.Betting
