module

public import Mathlib.Analysis.Asymptotics.Defs
public import Mathlib.MeasureTheory.Measure.Real
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Real
public import Mathlib.Topology.Algebra.InfiniteSum.Defs

/-! # Standalone extraction for `Wang2026Almost.ae_not_summable_of_isBigOmegaInProb`
Definitions are copied verbatim; theorem proofs are replaced by `sorry`.
Auto-generated by ChallengeGen. -/

set_option quotPrecheck false

-- The options the project is built with.
set_option autoImplicit false
set_option relaxedAutoImplicit false

-- Namespace stubs (so later `open`s resolve).
namespace MeasureTheory
end MeasureTheory
namespace ProbabilityTheory
end ProbabilityTheory
namespace Wang2026Almost
end Wang2026Almost

-- ═══ Wang2026Almost.Mathlib.Probability.AsymptoticsInProbability ═══
@[expose] public section
open Filter MeasureTheory Asymptotics
namespace ProbabilityTheory
variable {Ω : Type*} {mΩ : MeasurableSpace Ω} (P : Measure Ω)

/-- `X n = Ω_p(a n)`: for every `ε > 0` there is `δ > 0` such that `P(|X n| ≥ δ a n) ≥ 1 - ε`
for all but finitely many `n`. -/
def IsBigOmegaInProb (X : ℕ → Ω → ℝ) (a : ℕ → ℝ) : Prop :=
  ∀ ε : ℝ, 0 < ε → ∃ δ : ℝ, 0 < δ ∧ ∀ᶠ n in atTop, 1 - ε ≤ P.real {ω | δ * a n ≤ |X n ω|}

end ProbabilityTheory
end

-- ═══ Wang2026Almost.WAR2026.Theorem2_2 ═══
@[expose] public section
open MeasureTheory ProbabilityTheory Filter
namespace Wang2026Almost
variable {Ω : Type*} {mΩ : MeasurableSpace Ω} {P' : Measure Ω} [IsProbabilityMeasure P']

/-- **Theorem 2.2** (Wang, Agrawal, Ramdas 2026): if `Z n` are (almost surely) nonnegative random
variables with `Z n = Ω_p(n⁻¹)`, then `∑ Z n = ∞` almost surely. -/
theorem ae_not_summable_of_isBigOmegaInProb {Z : ℕ → Ω → ℝ} (hZ : ∀ n, AEMeasurable (Z n) P')
    (hnn : ∀ n, 0 ≤ᵐ[P'] Z n) (hΩ : IsBigOmegaInProb P' Z (fun n ↦ (n : ℝ)⁻¹)) :
    ∀ᵐ ω ∂P', ¬ Summable (fun n ↦ Z n ω) := sorry

end Wang2026Almost
end
