module

public import Mathlib.Analysis.SpecialFunctions.Log.Basic
public import Mathlib.MeasureTheory.Integral.Bochner.Basic
public import Mathlib.Probability.IdentDistrib
public import Mathlib.Probability.Independence.InfinitePi
public import Mathlib.Probability.Kernel.Basic
public import Mathlib.Probability.Kernel.IonescuTulcea.Traj
public import Mathlib.Probability.Process.FiniteDimensionalLaws
public import Mathlib.Probability.HasCondDistrib
public import Mathlib.MeasureTheory.Measure.ProbabilityMeasure
public import Mathlib.Probability.Independence.Basic
public import Mathlib.Probability.Independence.Conditional
public import Mathlib.MeasureTheory.Measure.SubFinite
public import Mathlib.Probability.Kernel.RadonNikodym
public import Mathlib.MeasureTheory.MeasurableSpace.Embedding
public import Mathlib.Order.Restriction
public import Mathlib.Probability.Kernel.IonescuTulcea.Maps
public import Mathlib.Analysis.Normed.Ring.Basic
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Basic
public import Mathlib.Probability.Kernel.Composition.MapComap
public import Mathlib.MeasureTheory.Measure.WithDensity
public import Mathlib.Probability.Distributions.Beta
public import Mathlib.MeasureTheory.Measure.Dirac.Basic
public import Mathlib.MeasureTheory.Measure.Dirac.Def
public import Mathlib.Probability.HasLaw
public import Mathlib.Analysis.SpecialFunctions.Log.Deriv
public import Mathlib.MeasureTheory.Integral.IntervalIntegral.FundThmCalculus
public import Mathlib.Probability.Martingale.Convergence
public import Mathlib.Probability.Martingale.Basic
public import Mathlib.MeasureTheory.Integral.Prod
public import Mathlib.MeasureTheory.Integral.Bochner.Set
public import Mathlib.Topology.Algebra.InfiniteSum.Real
public import Mathlib.Analysis.Asymptotics.Defs
public import Mathlib.MeasureTheory.Function.ConvergenceInDistribution
public import Mathlib.MeasureTheory.Measure.Portmanteau
public import Mathlib.MeasureTheory.Measure.Real
public import Mathlib.Probability.Moments.SubGaussian
public import Mathlib.Analysis.PSeries
public import Mathlib.Analysis.Calculus.Deriv.MeanValue
public import Mathlib.Probability.Process.Adapted
public import Mathlib.Topology.Order.Compact
public import Mathlib.Order.Filter.Extr
public import Mathlib.Order.CompletePartialOrder
public import Mathlib.Probability.Martingale.BorelCantelli
public import Mathlib.Probability.Moments.Variance
public import Mathlib.Analysis.Convex.SpecificFunctions.Basic
public import Mathlib.Analysis.SpecialFunctions.Pow.NNReal

/-! # Standalone extraction for `Wang2026Almost.tendsto_mixtureWealth_betaMixture`
Definitions are copied verbatim; theorem proofs are replaced by `sorry`.
Auto-generated by ChallengeGen. -/

set_option quotPrecheck false

-- The options the project is built with.
set_option autoImplicit false
set_option relaxedAutoImplicit false

-- Namespace stubs (so later `open`s resolve).
namespace MeasureTheory
end MeasureTheory
namespace Learning.Betting
end Learning.Betting
namespace ProbabilityTheory
end ProbabilityTheory
namespace Wang2026Almost
end Wang2026Almost
namespace Learning
end Learning

-- ═══ Wang2026Almost.LeanMachineLearning.Betting.Wealth ═══
@[expose] public section
open MeasureTheory Finset
namespace Learning.Betting
variable {Ω : Type*}

/-- The wealth after `n` rounds of the predictable plug-in betting strategy `lam` on the
observations `X`, testing the null mean `m`: `∏_{k < n} (1 + lam k (X k - m))`. -/
noncomputable def wealth (m : ℝ) (lam X : ℕ → Ω → ℝ) (n : ℕ) (ω : Ω) : ℝ :=
  ∏ k ∈ range n, (1 + lam k ω * (X k ω - m))

/-- The wealth of the fixed-fraction strategy betting the fraction `l` at every round. -/
noncomputable def fixedWealth (m l : ℝ) (X : ℕ → Ω → ℝ) : ℕ → Ω → ℝ := wealth m (fun _ _ ↦ l) X

/-- The wealth of the mixture strategy with mixing distribution `π` on the bet fractions:
`∫ fixedWealth m l X n ∂π(l)`. -/
noncomputable def mixtureWealth (m : ℝ) (π : Measure ℝ) (X : ℕ → Ω → ℝ) (n : ℕ) (ω : Ω) : ℝ :=
  ∫ l, fixedWealth m l X n ω ∂π

end Learning.Betting
end

-- ═══ Wang2026Almost.WAR2026.Mixtures ═══
@[expose] public section
open MeasureTheory ProbabilityTheory
namespace Wang2026Almost

/-- The mixing distribution of the universal portfolio strategy: the Beta distribution with
parameters `a, b` rescaled to `[-1, 1]`. -/
noncomputable def betaMixture (a b : ℝ) : Measure ℝ :=
  (betaMeasure a b).map (fun x ↦ ((2 : ℕ) : ℝ) * x - 1)

end Wang2026Almost
end

-- ═══ Wang2026Almost.WAR2026.Proposition3_2 ═══
@[expose] public section
open MeasureTheory ProbabilityTheory Filter Learning Learning.Betting
open scoped Topology ENNReal
namespace Wang2026Almost
variable {Ω : Type*} {mΩ : MeasurableSpace Ω} {P' : Measure Ω} [IsProbabilityMeasure P'] {P : Measure ℝ} [IsProbabilityMeasure P] {m : ℝ}

/-- **Proposition 3.2, universal portfolio** (Wang, Agrawal, Ramdas 2026): under every
non-degenerate null distribution on `[0, 1]`, the wealth of the mixture strategy with a rescaled
Beta mixing distribution converges to `0` almost surely. -/
theorem tendsto_mixtureWealth_betaMixture (hP : ∀ᵐ x ∂P, x ∈ Set.Icc (0 : ℝ) 1)
    (hm : ∫ x, x ∂P = m) (hnd : P ≠ Measure.dirac m) {X : ℕ → Ω → ℝ} (hX : ∀ n, Measurable (X n))
    (hindep : iIndepFun X P')
    (hlaw : ∀ n, HasLaw (X n) P P') {a b : ℝ} (ha : 0 < a) (hb : 0 < b) :
    ∀ᵐ ω ∂P', Tendsto (fun n ↦ mixtureWealth m (betaMixture a b) X n ω) atTop (𝓝 0) := sorry

end Wang2026Almost
end
