module

public import Mathlib.Analysis.SpecialFunctions.Log.Basic
public import Mathlib.MeasureTheory.Integral.Bochner.Basic
public import Mathlib.Probability.IdentDistrib
public import Mathlib.Probability.Independence.InfinitePi
public import Mathlib.Probability.Kernel.Basic
public import Mathlib.Probability.Kernel.IonescuTulcea.Traj
public import Mathlib.Probability.Process.FiniteDimensionalLaws
public import Mathlib.Probability.HasCondDistrib
public import Mathlib.MeasureTheory.Measure.ProbabilityMeasure
public import Mathlib.Probability.Independence.Basic
public import Mathlib.Probability.Independence.Conditional
public import Mathlib.MeasureTheory.Measure.SubFinite
public import Mathlib.Probability.Kernel.RadonNikodym
public import Mathlib.MeasureTheory.MeasurableSpace.Embedding
public import Mathlib.Order.Restriction
public import Mathlib.Probability.Kernel.IonescuTulcea.Maps
public import Mathlib.Analysis.Normed.Ring.Basic
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Basic
public import Mathlib.Probability.Kernel.Composition.MapComap
public import Mathlib.MeasureTheory.Function.ConvergenceInDistribution
public import Mathlib.MeasureTheory.Measure.Dirac.Basic
public import Mathlib.MeasureTheory.Measure.Dirac.Def
public import Mathlib.Probability.HasLaw
public import Mathlib.Probability.Moments.Basic
public import Mathlib.Probability.Distributions.Gamma

/-! # Standalone extraction for `Wang2026Almost.not_bddAbove_logRegret_of_tendsto_wealth_zero`
Definitions are copied verbatim; theorem proofs are replaced by `sorry`.
Auto-generated by ChallengeGen. -/

set_option quotPrecheck false

-- The options the project is built with.
set_option autoImplicit false
set_option relaxedAutoImplicit false

-- Namespace stubs (so later `open`s resolve).
namespace MeasureTheory
end MeasureTheory
namespace Learning.Betting
end Learning.Betting
namespace ProbabilityTheory
end ProbabilityTheory
namespace Learning
end Learning
namespace Wang2026Almost
end Wang2026Almost

-- ═══ Wang2026Almost.LeanMachineLearning.Betting.Wealth ═══
@[expose] public section
open MeasureTheory Finset
namespace Learning.Betting
variable {Ω : Type*}

/-- The range `[-1 / (1 - m), 1 / m]` of the bet fractions for which the wealth stays
nonnegative when the observations are in `[0, 1]`. -/
def fractionRange (m : ℝ) : Set ℝ := Set.Icc (-1 / (1 - m)) (1 / m)

/-- The wealth after `n` rounds of the predictable plug-in betting strategy `lam` on the
observations `X`, testing the null mean `m`: `∏_{k < n} (1 + lam k (X k - m))`. -/
noncomputable def wealth (m : ℝ) (lam X : ℕ → Ω → ℝ) (n : ℕ) (ω : Ω) : ℝ :=
  ∏ k ∈ range n, (1 + lam k ω * (X k ω - m))

/-- The wealth of the fixed-fraction strategy betting the fraction `l` at every round. -/
noncomputable def fixedWealth (m l : ℝ) (X : ℕ → Ω → ℝ) : ℕ → Ω → ℝ := wealth m (fun _ _ ↦ l) X

/-- The best-in-hindsight log-wealth after `n` rounds:
`log (sup_{l ∈ fractionRange m} fixedWealth m l X n)`. -/
noncomputable def hindsightLogWealth (m : ℝ) (X : ℕ → Ω → ℝ) (n : ℕ) (ω : Ω) : ℝ :=
  Real.log (⨆ l : fractionRange m, fixedWealth m (l : ℝ) X n ω)

/-- The regret of the strategy `lam` after `n` rounds: the best-in-hindsight log-wealth minus its
log-wealth. -/
noncomputable def logRegret (m : ℝ) (lam X : ℕ → Ω → ℝ) (n : ℕ) (ω : Ω) : ℝ :=
  hindsightLogWealth m X n ω - Real.log (wealth m lam X n ω)

end Learning.Betting
end

-- ═══ Wang2026Almost.WAR2026.Theorem5_1 ═══
@[expose] public section
open MeasureTheory ProbabilityTheory Filter Learning Learning.Betting
open scoped Topology
namespace Wang2026Almost
variable {Ω : Type*} {mΩ : MeasurableSpace Ω} {P' : Measure Ω} [IsProbabilityMeasure P'] {P : Measure ℝ} [IsProbabilityMeasure P] {m : ℝ}

/-- **Theorem 5.1, unbounded regret** (Wang, Agrawal, Ramdas 2026): a null-bankrupt betting
strategy has unbounded regret against the best-in-hindsight wealth on almost all paths:
`sup_n (L*_n - log W_n) = ∞` (the wealth may also vanish after finitely many rounds, in which
case the regret is infinite from that round on). -/
theorem not_bddAbove_logRegret_of_tendsto_wealth_zero (hm : m ∈ Set.Ioo 0 1)
    {lam X : ℕ → Ω → ℝ} (h : ∀ᵐ ω ∂P', Tendsto (fun n ↦ wealth m lam X n ω) atTop (𝓝 0)) :
    ∀ᵐ ω ∂P', (∃ n, wealth m lam X n ω = 0) ∨
      ¬ BddAbove (Set.range fun n ↦ logRegret m lam X n ω) := sorry

end Wang2026Almost
end
