module

public import Mathlib.Analysis.SpecialFunctions.Log.Basic
public import Mathlib.MeasureTheory.Integral.Bochner.Basic
public import Mathlib.Probability.IdentDistrib
public import Mathlib.Probability.Independence.InfinitePi
public import Mathlib.Probability.Kernel.Basic
public import Mathlib.Probability.Kernel.IonescuTulcea.Traj
public import Mathlib.Probability.Process.FiniteDimensionalLaws
public import Mathlib.Probability.HasCondDistrib
public import Mathlib.MeasureTheory.Measure.ProbabilityMeasure
public import Mathlib.Probability.Independence.Basic
public import Mathlib.Probability.Independence.Conditional
public import Mathlib.MeasureTheory.Measure.SubFinite
public import Mathlib.Probability.Kernel.RadonNikodym
public import Mathlib.MeasureTheory.MeasurableSpace.Embedding
public import Mathlib.Order.Restriction
public import Mathlib.Probability.Kernel.IonescuTulcea.Maps
public import Mathlib.Analysis.Normed.Ring.Basic
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Basic
public import Mathlib.Probability.Kernel.Composition.MapComap
public import Mathlib.Order.Filter.Extr
public import Mathlib.Order.CompletePartialOrder
public import Mathlib.Probability.Martingale.BorelCantelli
public import Mathlib.Analysis.Asymptotics.Defs
public import Mathlib.MeasureTheory.Measure.Real
public import Mathlib.MeasureTheory.Function.ConvergenceInDistribution
public import Mathlib.Probability.Distributions.Gaussian.Real
public import Mathlib.Probability.HasLaw
public import Mathlib.Probability.Moments.Variance

/-! # Standalone extraction for `Wang2026Almost.grapa_bankrupt`
Definitions are copied verbatim; theorem proofs are replaced by `sorry`.
Auto-generated by ChallengeGen. -/

set_option quotPrecheck false

-- The options the project is built with.
set_option autoImplicit false
set_option relaxedAutoImplicit false

-- Namespace stubs (so later `open`s resolve).
namespace MeasureTheory
end MeasureTheory
namespace Learning.Betting
end Learning.Betting
namespace ProbabilityTheory
end ProbabilityTheory
namespace Learning
end Learning
namespace Wang2026Almost
end Wang2026Almost

-- ═══ Wang2026Almost.LeanMachineLearning.Betting.Wealth ═══
@[expose] public section
open MeasureTheory Finset
namespace Learning.Betting
variable {Ω : Type*}

/-- The range `[-1 / (1 - m), 1 / m]` of the bet fractions for which the wealth stays
nonnegative when the observations are in `[0, 1]`. -/
def fractionRange (m : ℝ) : Set ℝ := Set.Icc (-1 / (1 - m)) (1 / m)

/-- The wealth after `n` rounds of the predictable plug-in betting strategy `lam` on the
observations `X`, testing the null mean `m`: `∏_{k < n} (1 + lam k (X k - m))`. -/
noncomputable def wealth (m : ℝ) (lam X : ℕ → Ω → ℝ) (n : ℕ) (ω : Ω) : ℝ :=
  ∏ k ∈ range n, (1 + lam k ω * (X k ω - m))

/-- The wealth of the fixed-fraction strategy betting the fraction `l` at every round. -/
noncomputable def fixedWealth (m l : ℝ) (X : ℕ → Ω → ℝ) : ℕ → Ω → ℝ := wealth m (fun _ _ ↦ l) X

end Learning.Betting
end

-- ═══ Wang2026Almost.LeanMachineLearning.Betting.Strategies ═══
@[expose] public section
open Finset
namespace Learning.Betting
variable {Ω : Type*}

/-- `lam` is a *plug-in* bet fraction process for the observations `X`: each `lam n` is a
measurable function of the first `n` observations `X 0, …, X (n - 1)`. -/
def IsPlugIn (X lam : ℕ → Ω → ℝ) : Prop :=
  ∀ n, ∃ f : (Fin n → ℝ) → ℝ, Measurable f ∧ ∀ ω, lam n ω = f (fun k ↦ X k ω)

/-- `gr` is a GRAPA (follow-the-leader) bet fraction process for the observations `X`: a plug-in
strategy such that `gr n` is a maximizer of the hindsight wealth `l ↦ fixedWealth m l X n` over
`fractionRange m` (for `n = 0`, any value in `fractionRange m`). -/
def IsGrapa (m : ℝ) (X gr : ℕ → Ω → ℝ) : Prop :=
  IsPlugIn X gr ∧ ∀ n ω, gr n ω ∈ fractionRange m ∧
    IsMaxOn (fun l ↦ fixedWealth m l X n ω) (fractionRange m) (gr n ω)

end Learning.Betting
end

-- ═══ Wang2026Almost.Mathlib.Probability.AsymptoticsInProbability ═══
@[expose] public section
open Filter MeasureTheory Asymptotics
namespace ProbabilityTheory
variable {Ω : Type*} {mΩ : MeasurableSpace Ω} (P : Measure Ω)

/-- `X n = Ω_p(a n)`: for every `ε > 0` there is `δ > 0` such that `P(|X n| ≥ δ a n) ≥ 1 - ε`
for all but finitely many `n`. -/
def IsBigOmegaInProb (X : ℕ → Ω → ℝ) (a : ℕ → ℝ) : Prop :=
  ∀ ε : ℝ, 0 < ε → ∃ δ : ℝ, 0 < δ ∧ ∀ᶠ n in atTop, 1 - ε ≤ P.real {ω | δ * a n ≤ |X n ω|}

end ProbabilityTheory
end

-- ═══ Wang2026Almost.WAR2026.Proposition2_6 ═══
@[expose] public section
open MeasureTheory ProbabilityTheory Filter Learning Learning.Betting Real Asymptotics
open scoped Topology ProbabilityTheory
namespace Wang2026Almost
variable {Ω : Type*} {mΩ : MeasurableSpace Ω} {P' : Measure Ω} [IsProbabilityMeasure P'] {P : Measure ℝ} [IsProbabilityMeasure P] {m : ℝ}

/-- **Proposition 2.6** (Wang, Agrawal, Ramdas 2026): for i.i.d. observations `X` of law `P` on
`[0, 1]` with mean `m` and variance `σ² > 0`, a GRAPA bet fraction process `gr` (`gr n` maximizes
the hindsight wealth of the first `n` rounds) satisfies the almost sure Bahadur expansion
`√n gr n = S n / (σ² √n) + o_{a.s.}(n^{-1/4} log n)`, `S n = ∑_{k < n} (X k - m)`, hence
`√n gr n → N(0, σ⁻²)` in distribution and `gr n = Ω_p(n^{-1/2})`, and the GRAPA wealth process
converges to `0` almost surely. -/
theorem grapa_bankrupt (hP : ∀ᵐ x ∂P, x ∈ Set.Icc (0 : ℝ) 1) (hm : ∫ x, x ∂P = m)
    (hvar : 0 < Var[id; P]) {X gr : ℕ → Ω → ℝ} (hX : ∀ n, Measurable (X n))
    (hindep : iIndepFun X P')
    (hlaw : ∀ n, HasLaw (X n) P P') (hgr : IsGrapa m X gr) :
    (∀ᵐ ω ∂P', (fun n : ℕ ↦ √n * gr n ω - (∑ k ∈ Finset.range n, (X k ω - m)) / (Var[id; P] * √n))
        =o[atTop] fun n : ℕ ↦ (n : ℝ) ^ (-1 / 4 : ℝ) * Real.log n) ∧
      TendstoInDistribution (fun (n : ℕ) ω ↦ √n * gr n ω) atTop (id : ℝ → ℝ) (fun _ ↦ P')
        (gaussianReal 0 ((Var[id; P])⁻¹).toNNReal) ∧
      IsBigOmegaInProb P' gr (fun n ↦ (n : ℝ) ^ (-1 / 2 : ℝ)) ∧
      ∀ᵐ ω ∂P', Tendsto (fun n ↦ wealth m gr X n ω) atTop (𝓝 0) := sorry

end Wang2026Almost
end
