module

public import Mathlib.Analysis.SpecialFunctions.Log.Basic
public import Mathlib.MeasureTheory.Integral.Bochner.Basic
public import Mathlib.Probability.IdentDistrib
public import Mathlib.Probability.Independence.InfinitePi
public import Mathlib.Probability.Kernel.Basic
public import Mathlib.Probability.Kernel.IonescuTulcea.Traj
public import Mathlib.Probability.Process.FiniteDimensionalLaws
public import Mathlib.Probability.HasCondDistrib
public import Mathlib.MeasureTheory.Measure.ProbabilityMeasure
public import Mathlib.Probability.Independence.Basic
public import Mathlib.Probability.Independence.Conditional
public import Mathlib.MeasureTheory.Measure.SubFinite
public import Mathlib.Probability.Kernel.RadonNikodym
public import Mathlib.MeasureTheory.MeasurableSpace.Embedding
public import Mathlib.Order.Restriction
public import Mathlib.Probability.Kernel.IonescuTulcea.Maps
public import Mathlib.Analysis.Normed.Ring.Basic
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Basic
public import Mathlib.Probability.Kernel.Composition.MapComap
public import Mathlib.Probability.Process.Adapted

/-! # Standalone extraction for `Wang2026Almost.exists_improve`
Definitions are copied verbatim; theorem proofs are replaced by `sorry`.
Auto-generated by ChallengeGen. -/

set_option quotPrecheck false

-- The options the project is built with.
set_option autoImplicit false
set_option relaxedAutoImplicit false

-- Namespace stubs (so later `open`s resolve).
namespace MeasureTheory
end MeasureTheory
namespace Learning.Betting
end Learning.Betting
namespace Wang2026Almost
end Wang2026Almost

-- ═══ Wang2026Almost.LeanMachineLearning.Betting.Wealth ═══
@[expose] public section
open MeasureTheory Finset
namespace Learning.Betting
variable {Ω : Type*}

/-- The range `[-1 / (1 - m), 1 / m]` of the bet fractions for which the wealth stays
nonnegative when the observations are in `[0, 1]`. -/
def fractionRange (m : ℝ) : Set ℝ := Set.Icc (-1 / (1 - m)) (1 / m)

/-- The wealth after `n` rounds of the predictable plug-in betting strategy `lam` on the
observations `X`, testing the null mean `m`: `∏_{k < n} (1 + lam k (X k - m))`. -/
noncomputable def wealth (m : ℝ) (lam X : ℕ → Ω → ℝ) (n : ℕ) (ω : Ω) : ℝ :=
  ∏ k ∈ range n, (1 + lam k ω * (X k ω - m))

end Learning.Betting
end

-- ═══ Wang2026Almost.WAR2026.Leverage ═══
@[expose] public section
open Learning.Betting
namespace Wang2026Almost
variable {Ω : Type*}

/-- The minimum possible wealth after round `n`, given the information available before `X n`
is revealed: `min_{x ∈ {0, 1}} wealth m lam X n * (1 + lam n (x - m))`. -/
noncomputable def nextWealthMin (m : ℝ) (lam X : ℕ → Ω → ℝ) (n : ℕ) (ω : Ω) : ℝ :=
  min (wealth m lam X n ω * (1 + lam n ω * (0 - m))) (wealth m lam X n ω * (1 + lam n ω * (1 - m)))

/-- The `ρ`-predictably non-bankrupt event of the strategy `lam`: at every round, the next
wealth is guaranteed to stay above `ρ`. -/
def pnbEvent (m ρ : ℝ) (lam X : ℕ → Ω → ℝ) : Set Ω := {ω | ∀ n, ρ < nextWealthMin m lam X n ω}

end Wang2026Almost
end

-- ═══ Wang2026Almost.WAR2026.Theorem4_1 ═══
@[expose] public section
open MeasureTheory Filter Learning.Betting
open scoped Topology
namespace Wang2026Almost
variable {Ω : Type*} {mΩ : MeasurableSpace Ω}

/-- **Theorem 4.1** (improvability on predictably non-bankrupt paths, Wang, Agrawal, Ramdas
2026). Let `lam` be a betting strategy, predictable for a filtration `ℱ` to which the
observations `X` are adapted with a lag, and let `ρ ∈ (0, 1)`. There is another betting strategy
`gam`, predictable for `ℱ`, whose bet fractions are in `[-1 / (1 - m), 1 / m]` whenever those of
`lam` are, and whose wealth is `(W n - ρ) / (1 - ρ)` on the `ρ`-predictably non-bankrupt event
`N^ρ` of `lam`. Consequently, on `N^ρ`: `W' n > W n` when `W n > 1`, `W' n / W n → 1 / (1 - ρ)`
when `W n → ∞`, `W' n < W n` when `W n < 1`, and `W' n → (w - ρ) / (1 - ρ) < w` when
`W n → w < 1`. -/
theorem exists_improve {ℱ : Filtration ℕ mΩ} {m ρ : ℝ} (hm : m ∈ Set.Ioo 0 1)
    (hρ : ρ ∈ Set.Ioo 0 1) {lam X : ℕ → Ω → ℝ} (hlam : Adapted ℱ lam)
    (hX : ∀ n, Measurable[ℱ (n + 1)] (X n)) :
    ∃ gam : ℕ → Ω → ℝ, Adapted ℱ gam ∧
      (∀ n ω, lam n ω ∈ fractionRange m → gam n ω ∈ fractionRange m) ∧
      ∀ ω ∈ pnbEvent m ρ lam X,
        (∀ n, wealth m gam X n ω = (wealth m lam X n ω - ρ) / (1 - ρ)) ∧
        (∀ n, 1 < wealth m lam X n ω → wealth m lam X n ω < wealth m gam X n ω) ∧
        (Tendsto (fun n ↦ wealth m lam X n ω) atTop atTop →
          Tendsto (fun n ↦ wealth m gam X n ω / wealth m lam X n ω) atTop (𝓝 (1 / (1 - ρ)))) ∧
        (∀ n, wealth m lam X n ω < 1 → wealth m gam X n ω < wealth m lam X n ω) ∧
        ∀ w, Tendsto (fun n ↦ wealth m lam X n ω) atTop (𝓝 w) → w < 1 →
          Tendsto (fun n ↦ wealth m gam X n ω) atTop (𝓝 ((w - ρ) / (1 - ρ))) ∧
            (w - ρ) / (1 - ρ) < w := sorry

end Wang2026Almost
end
