module

public import Mathlib.Probability.CentralLimitTheorem
public import Mathlib.Probability.IdentDistrib
public import Mathlib.Probability.Independence.Basic
public import Mathlib.Probability.Moments.Variance
public import Mathlib.Analysis.PSeries
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Real
public import Mathlib.Topology.Algebra.InfiniteSum.Defs
public import Mathlib.MeasureTheory.Integral.Bochner.Set
public import Mathlib.Topology.Algebra.InfiniteSum.Real
public import Mathlib.Analysis.Asymptotics.Defs
public import Mathlib.MeasureTheory.Function.ConvergenceInDistribution
public import Mathlib.MeasureTheory.Measure.Portmanteau
public import Mathlib.MeasureTheory.Measure.Real

/-! # Standalone extraction for `Wang2026Almost.ae_not_summable_sum_sq_div_sq`
Definitions are copied verbatim; theorem proofs are replaced by `sorry`.
Auto-generated by ChallengeGen. -/

set_option quotPrecheck false

-- The options the project is built with.
set_option autoImplicit false
set_option relaxedAutoImplicit false

-- Namespace stubs (so later `open`s resolve).
namespace MeasureTheory
end MeasureTheory
namespace ProbabilityTheory
end ProbabilityTheory
namespace Wang2026Almost
end Wang2026Almost

-- ═══ Wang2026Almost.WAR2026.Corollary2_3 ═══
@[expose] public section
open MeasureTheory ProbabilityTheory Filter
open scoped ProbabilityTheory NNReal
namespace Wang2026Almost
variable {Ω : Type*} {mΩ : MeasurableSpace Ω} {P' : Measure Ω} [IsProbabilityMeasure P']

/-- **Corollary 2.3** (Wang, Agrawal, Ramdas 2026): for i.i.d. random variables `Y n` with mean
`0` and variance `σ² > 0`, the series `∑ S n ^ 2 / n ^ 2` of the partial sums
`S n = Y 0 + … + Y (n - 1)` diverges almost surely. -/
theorem ae_not_summable_sum_sq_div_sq {Y : ℕ → Ω → ℝ} (hindep : iIndepFun Y P')
    (hident : ∀ n, IdentDistrib (Y n) (Y 0) P' P') (hL2 : MemLp (Y 0) 2 P')
    (h0 : P'[Y 0] = 0) (hvar : 0 < Var[Y 0; P']) :
    ∀ᵐ ω ∂P', ¬ Summable (fun n ↦ (∑ k ∈ Finset.range (n + 1), Y k ω) ^ 2 / (n + 1) ^ 2) := sorry

end Wang2026Almost
end
