module

public import Mathlib.Analysis.SpecialFunctions.Log.Basic
public import Mathlib.MeasureTheory.Integral.Bochner.Basic
public import Mathlib.Probability.IdentDistrib
public import Mathlib.Probability.Independence.InfinitePi
public import Mathlib.Probability.Kernel.Basic
public import Mathlib.Probability.Kernel.IonescuTulcea.Traj
public import Mathlib.Probability.Process.FiniteDimensionalLaws
public import Mathlib.Probability.HasCondDistrib
public import Mathlib.MeasureTheory.Measure.ProbabilityMeasure
public import Mathlib.Probability.Independence.Basic
public import Mathlib.Probability.Independence.Conditional
public import Mathlib.MeasureTheory.Measure.SubFinite
public import Mathlib.Probability.Kernel.RadonNikodym
public import Mathlib.MeasureTheory.MeasurableSpace.Embedding
public import Mathlib.Order.Restriction
public import Mathlib.Probability.Kernel.IonescuTulcea.Maps
public import Mathlib.Analysis.Normed.Ring.Basic
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Basic
public import Mathlib.Probability.Kernel.Composition.MapComap
public import Mathlib.Order.Filter.Extr
public import Mathlib.Order.CompletePartialOrder
public import Mathlib.Probability.Martingale.BorelCantelli
public import Mathlib.Analysis.Asymptotics.Defs
public import Mathlib.MeasureTheory.Function.ConvergenceInDistribution
public import Mathlib.MeasureTheory.Measure.Portmanteau
public import Mathlib.MeasureTheory.Measure.Real
public import Mathlib.Probability.HasLaw
public import Mathlib.Probability.Moments.Variance
public import Mathlib.Probability.Process.Adapted
public import Mathlib.Topology.Order.Compact
public import Mathlib.MeasureTheory.Measure.Dirac.Basic
public import Mathlib.Probability.Distributions.Gaussian.Real
public import Mathlib.Probability.CentralLimitTheorem
public import Mathlib.Probability.StrongLaw
public import Mathlib.Probability.Moments.SubGaussian
public import Mathlib.Analysis.PSeries
public import Mathlib.Analysis.SpecialFunctions.Pow.Real
public import Mathlib.MeasureTheory.Integral.Bochner.Set
public import Mathlib.Topology.Algebra.InfiniteSum.Real
public import Mathlib.Probability.Martingale.Convergence
public import Mathlib.Probability.Martingale.Basic
public import Mathlib.Analysis.Calculus.Deriv.MeanValue
public import Mathlib.Analysis.SpecialFunctions.Log.Deriv

/-! # Standalone extraction for `Wang2026Almost.hedged_bankrupt`
Definitions are copied verbatim; theorem proofs are replaced by `sorry`.
Auto-generated by ChallengeGen. -/

set_option quotPrecheck false

-- The options the project is built with.
set_option autoImplicit false
set_option relaxedAutoImplicit false

-- Namespace stubs (so later `open`s resolve).
namespace MeasureTheory
end MeasureTheory
namespace Learning.Betting
end Learning.Betting
namespace ProbabilityTheory
end ProbabilityTheory
namespace Learning
end Learning
namespace Real
end Real
namespace Wang2026Almost
end Wang2026Almost

-- ═══ Wang2026Almost.LeanMachineLearning.Betting.Wealth ═══
@[expose] public section
open MeasureTheory Finset
namespace Learning.Betting
variable {Ω : Type*}

/-- The wealth after `n` rounds of the predictable plug-in betting strategy `lam` on the
observations `X`, testing the null mean `m`: `∏_{k < n} (1 + lam k (X k - m))`. -/
noncomputable def wealth (m : ℝ) (lam X : ℕ → Ω → ℝ) (n : ℕ) (ω : Ω) : ℝ :=
  ∏ k ∈ range n, (1 + lam k ω * (X k ω - m))

/-- The wealth of the hedged strategy based on `lam`: the equal mixture of the strategies `lam`
and `-lam`. -/
noncomputable def hedgedWealth (m : ℝ) (lam X : ℕ → Ω → ℝ) (n : ℕ) (ω : Ω) : ℝ :=
  (wealth m lam X n ω + wealth m (fun k ω ↦ -lam k ω) X n ω) / ((2 : ℕ) : ℝ)

end Learning.Betting
end

-- ═══ Wang2026Almost.LeanMachineLearning.Betting.Strategies ═══
@[expose] public section
open Finset
namespace Learning.Betting
variable {Ω : Type*}

/-- `lam` is a *plug-in* bet fraction process for the observations `X`: each `lam n` is a
measurable function of the first `n` observations `X 0, …, X (n - 1)`. -/
def IsPlugIn (X lam : ℕ → Ω → ℝ) : Prop :=
  ∀ n, ∃ f : (Fin n → ℝ) → ℝ, Measurable f ∧ ∀ ω, lam n ω = f (fun k ↦ X k ω)

/-- The bet fraction of the predictable hedging strategy at round `n` (after `n` observations),
for the variance estimate `v` and the confidence parameter `α`:
`√(2 log(2/α) / (v (n + 1) log (n + 2)))`, clipped to `[-C / (1 - m), C / m]`. -/
noncomputable def hedgeFraction (C α m v : ℝ) (n : ℕ) : ℝ :=
  max (-C / (1 - m))
    (min (√(((2 : ℕ) : ℝ) * Real.log (((2 : ℕ) : ℝ) / α) /
      (v * ((n : ℝ) + 1) * Real.log ((n + 2 : ℕ) : ℝ)))) (C / m))

end Learning.Betting
end

-- ═══ Wang2026Almost.Mathlib.Probability.AsymptoticsInProbability ═══
@[expose] public section
open Filter MeasureTheory Asymptotics
open scoped Topology
namespace ProbabilityTheory
variable {Ω : Type*} {mΩ : MeasurableSpace Ω} (P : Measure Ω)

/-- `X n = Ω_{a.s.}(a n)`: almost surely, the path `n ↦ X n ω` is `Ω(a n)`, that is
`a n = O(X n ω)`. -/
def IsBigOmegaAE (X : ℕ → Ω → ℝ) (a : ℕ → ℝ) : Prop :=
  ∀ᵐ ω ∂P, a =O[atTop] (fun n ↦ X n ω)

end ProbabilityTheory
end

-- ═══ Wang2026Almost.WAR2026.Proposition2_8 ═══
@[expose] public section
open MeasureTheory ProbabilityTheory Filter Learning Learning.Betting Real
open scoped Topology ProbabilityTheory
namespace Wang2026Almost
variable {Ω : Type*} {mΩ : MeasurableSpace Ω} {P' : Measure Ω} [IsProbabilityMeasure P'] {P : Measure ℝ} [IsProbabilityMeasure P] {m : ℝ}

/-- **Proposition 2.8** (Wang, Agrawal, Ramdas 2026): for i.i.d. observations `X` of law `P` on
`[0, 1]` with mean `m` and variance `σ² > 0`, and a plug-in variance estimate `v` (a measurable
function of the past observations) which is consistent (`v n → σ²` almost surely), the bet
fractions `hedgeFraction C α m (v n) n` of the predictable hedging strategy (`C, α ∈ (0, 1)`) are
`Ω_{a.s.}((n log n)^{-1/2})`, and the hedged wealth process converges to `0` almost surely. -/
theorem hedged_bankrupt (hP : ∀ᵐ x ∂P, x ∈ Set.Icc (0 : ℝ) 1) (hm : ∫ x, x ∂P = m)
    (hvar : 0 < Var[id; P]) {C α : ℝ} (hC : C ∈ Set.Ioo 0 1) (hα : α ∈ Set.Ioo 0 1)
    {X v : ℕ → Ω → ℝ} (hX : ∀ n, Measurable (X n))
    (hindep : iIndepFun X P') (hlaw : ∀ n, HasLaw (X n) P P')
    (hv : IsPlugIn X v) (hcons : ∀ᵐ ω ∂P', Tendsto (fun n ↦ v n ω) atTop (𝓝 Var[id; P])) :
    IsBigOmegaAE P' (fun n ω ↦ hedgeFraction C α m (v n ω) n)
        (fun n ↦ ((n : ℝ) * Real.log n) ^ (-1 / 2 : ℝ)) ∧
      ∀ᵐ ω ∂P', Tendsto (fun n ↦ hedgedWealth m (fun n ω ↦ hedgeFraction C α m (v n ω) n) X n ω)
        atTop (𝓝 0) := sorry

end Wang2026Almost
end
