module

public import Mathlib.Analysis.SpecialFunctions.Log.Basic
public import Mathlib.MeasureTheory.Integral.Bochner.Basic
public import Mathlib.Probability.IdentDistrib
public import Mathlib.Probability.Independence.InfinitePi
public import Mathlib.Probability.Kernel.Basic
public import Mathlib.Probability.Kernel.IonescuTulcea.Traj
public import Mathlib.Probability.Process.FiniteDimensionalLaws
public import Mathlib.Probability.HasCondDistrib
public import Mathlib.MeasureTheory.Measure.ProbabilityMeasure
public import Mathlib.Probability.Independence.Basic
public import Mathlib.Probability.Independence.Conditional
public import Mathlib.MeasureTheory.Measure.SubFinite
public import Mathlib.Probability.Kernel.RadonNikodym
public import Mathlib.MeasureTheory.MeasurableSpace.Embedding
public import Mathlib.Order.Restriction
public import Mathlib.Probability.Kernel.IonescuTulcea.Maps
public import Mathlib.Analysis.Normed.Ring.Basic
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Basic
public import Mathlib.Probability.Kernel.Composition.MapComap
public import Mathlib.Probability.HasLaw
public import Mathlib.Probability.Moments.SubGaussian
public import Mathlib.Probability.Martingale.Convergence
public import Mathlib.Probability.Martingale.Basic
public import Mathlib.MeasureTheory.Integral.Prod
public import Mathlib.MeasureTheory.Integral.Bochner.Set
public import Mathlib.Topology.Algebra.InfiniteSum.Real
public import Mathlib.Analysis.Asymptotics.Defs
public import Mathlib.MeasureTheory.Function.ConvergenceInDistribution
public import Mathlib.MeasureTheory.Measure.Portmanteau
public import Mathlib.MeasureTheory.Measure.Real
public import Mathlib.Analysis.PSeries
public import Mathlib.Analysis.Calculus.Deriv.MeanValue
public import Mathlib.Analysis.SpecialFunctions.Log.Deriv
public import Mathlib.Probability.Process.Adapted
public import Mathlib.Topology.Order.Compact
public import Mathlib.Order.Filter.Extr
public import Mathlib.Order.CompletePartialOrder
public import Mathlib.Probability.Martingale.BorelCantelli
public import Mathlib.MeasureTheory.Measure.Dirac.Basic
public import Mathlib.Probability.Moments.Variance
public import Mathlib.Analysis.Convex.SpecificFunctions.Basic
public import Mathlib.Analysis.SpecialFunctions.Pow.NNReal

/-! # Standalone extraction for `Wang2026Almost.tendsto_subgaussianMixtureTest`
Definitions are copied verbatim; theorem proofs are replaced by `sorry`.
Auto-generated by ChallengeGen. -/

set_option quotPrecheck false

-- The options the project is built with.
set_option autoImplicit false
set_option relaxedAutoImplicit false

-- Namespace stubs (so later `open`s resolve).
namespace MeasureTheory
end MeasureTheory
namespace Learning.Betting
end Learning.Betting
namespace ProbabilityTheory
end ProbabilityTheory
namespace Learning
end Learning
namespace Wang2026Almost
end Wang2026Almost

-- ═══ Wang2026Almost.LeanMachineLearning.Betting.Wealth ═══
@[expose] public section
open MeasureTheory Finset
namespace Learning.Betting
variable {Ω : Type*}

/-- The plug-in sub-Gaussian test process
`exp (∑_{k < n} ((X k - m)² - (X k - lam k)²) / 2)`: the likelihood ratio of `N(lam k, 1)`
against `N(m, 1)` on the observations. -/
noncomputable def subgaussianTest (m : ℝ) (lam X : ℕ → Ω → ℝ) (n : ℕ) (ω : Ω) : ℝ :=
  Real.exp (∑ k ∈ range n, ((X k ω - m) ^ 2 - (X k ω - lam k ω) ^ 2) / ((2 : ℕ) : ℝ))

/-- The mixture sub-Gaussian test process with mixing distribution `π`. -/
noncomputable def subgaussianMixtureTest (m : ℝ) (π : Measure ℝ) (X : ℕ → Ω → ℝ) (n : ℕ)
    (ω : Ω) : ℝ :=
  ∫ l, subgaussianTest m (fun _ _ ↦ l) X n ω ∂π

end Learning.Betting
end

-- ═══ Wang2026Almost.WAR2026.Theorem5_3 ═══
@[expose] public section
open MeasureTheory ProbabilityTheory Filter Learning Learning.Betting
open scoped Topology
namespace Wang2026Almost
variable {Ω : Type*} {mΩ : MeasurableSpace Ω} {P' : Measure Ω} [IsProbabilityMeasure P'] {P : Measure ℝ} [IsProbabilityMeasure P] {m : ℝ}

set_option linter.unusedSectionVars false in
/-- **Theorem 5.3** (no-cash criterion II, Wang, Agrawal, Ramdas 2026): for i.i.d. observations
`X` of a `1`-sub-Gaussian law `P` with mean `m`, and a probability measure `π` on `ℝ`, the
mixture test process `∫ exp (∑_{k < n} ((X k - m)² - (X k - l)²) / 2) ∂π(l)` converges almost
surely to `π({m})`. The paper assumes `P` non-degenerate; the proof does not use it. -/
@[nolint unusedArguments]
theorem tendsto_subgaussianMixtureTest (hP : HasSubgaussianMGF (fun x ↦ x - m) 1 P)
    {X : ℕ → Ω → ℝ} (hX : ∀ n, Measurable (X n))
    (hindep : iIndepFun X P')
    (hlaw : ∀ n, HasLaw (X n) P P') (π : Measure ℝ) [IsProbabilityMeasure π] :
    ∀ᵐ ω ∂P', Tendsto (fun n ↦ subgaussianMixtureTest m π X n ω) atTop (𝓝 (π.real {m})) := sorry

end Wang2026Almost
end
