module

public import Mathlib.Analysis.SpecialFunctions.Log.Basic
public import Mathlib.MeasureTheory.Integral.Bochner.Basic
public import Mathlib.Probability.IdentDistrib
public import Mathlib.Probability.Independence.InfinitePi
public import Mathlib.Probability.Kernel.Basic
public import Mathlib.Probability.Kernel.IonescuTulcea.Traj
public import Mathlib.Probability.Process.FiniteDimensionalLaws
public import Mathlib.Probability.HasCondDistrib
public import Mathlib.MeasureTheory.Measure.ProbabilityMeasure
public import Mathlib.Probability.Independence.Basic
public import Mathlib.Probability.Independence.Conditional
public import Mathlib.MeasureTheory.Measure.SubFinite
public import Mathlib.Probability.Kernel.RadonNikodym
public import Mathlib.MeasureTheory.MeasurableSpace.Embedding
public import Mathlib.Order.Restriction
public import Mathlib.Probability.Kernel.IonescuTulcea.Maps
public import Mathlib.Analysis.Normed.Ring.Basic
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Basic
public import Mathlib.Probability.Kernel.Composition.MapComap
public import Mathlib.Order.Filter.Extr
public import Mathlib.Order.CompletePartialOrder
public import Mathlib.Probability.Martingale.BorelCantelli
public import Mathlib.Analysis.Asymptotics.Defs
public import Mathlib.MeasureTheory.Function.ConvergenceInDistribution
public import Mathlib.MeasureTheory.Measure.Portmanteau
public import Mathlib.MeasureTheory.Measure.Real
public import Mathlib.Probability.Distributions.Gaussian.Real
public import Mathlib.Probability.HasLaw
public import Mathlib.Probability.Moments.Variance
public import Mathlib.Probability.StrongLaw
public import Mathlib.Probability.Process.Adapted
public import Mathlib.Topology.Order.Compact
public import Mathlib.Probability.Moments.SubGaussian
public import Mathlib.MeasureTheory.Measure.Dirac.Basic
public import Mathlib.Analysis.PSeries
public import Mathlib.Analysis.SpecialFunctions.Pow.Real
public import Mathlib.MeasureTheory.Integral.Bochner.Set
public import Mathlib.Topology.Algebra.InfiniteSum.Real
public import Mathlib.Probability.ConditionalExpectation
public import Mathlib.Probability.Kernel.Condexp
public import Mathlib.Probability.Martingale.Convergence
public import Mathlib.Probability.Martingale.Basic
public import Mathlib.Analysis.Calculus.Deriv.MeanValue
public import Mathlib.Analysis.SpecialFunctions.Log.Deriv
public import Mathlib.Probability.CentralLimitTheorem

/-! # Standalone extraction for `Wang2026Almost.agrapa_bankrupt`
Definitions are copied verbatim; theorem proofs are replaced by `sorry`.
Auto-generated by ChallengeGen. -/

set_option quotPrecheck false

-- The options the project is built with.
set_option autoImplicit false
set_option relaxedAutoImplicit false

-- Namespace stubs (so later `open`s resolve).
namespace MeasureTheory
end MeasureTheory
namespace Learning.Betting
end Learning.Betting
namespace ProbabilityTheory
end ProbabilityTheory
namespace Learning
end Learning
namespace Real
end Real
namespace Wang2026Almost
end Wang2026Almost

-- ═══ Wang2026Almost.LeanMachineLearning.Betting.Wealth ═══
@[expose] public section
open MeasureTheory Finset
namespace Learning.Betting
variable {Ω : Type*}

/-- The wealth after `n` rounds of the predictable plug-in betting strategy `lam` on the
observations `X`, testing the null mean `m`: `∏_{k < n} (1 + lam k (X k - m))`. -/
noncomputable def wealth (m : ℝ) (lam X : ℕ → Ω → ℝ) (n : ℕ) (ω : Ω) : ℝ :=
  ∏ k ∈ range n, (1 + lam k ω * (X k ω - m))

end Learning.Betting
end

-- ═══ Wang2026Almost.LeanMachineLearning.Betting.Strategies ═══
@[expose] public section
open Finset
namespace Learning.Betting
variable {Ω : Type*}

/-- The empirical mean of the first `n` observations. -/
noncomputable def empMean (X : ℕ → Ω → ℝ) (n : ℕ) (ω : Ω) : ℝ := (∑ k ∈ range n, X k ω) / n

/-- The empirical variance of the first `n` observations. -/
noncomputable def empVar (X : ℕ → Ω → ℝ) (n : ℕ) (ω : Ω) : ℝ :=
  (∑ k ∈ range n, (X k ω - empMean X n ω) ^ 2) / n

/-- The approximate GRAPA (aGRAPA) bet fraction with clipping constant `C`: after `n`
observations, `(μ̂ - m) / (σ̂² + (μ̂ - m)²)` for the empirical mean `μ̂` and variance `σ̂²`,
clipped to `[-C / (1 - m), C / m]`. -/
noncomputable def agrapaFraction (C m : ℝ) (X : ℕ → Ω → ℝ) (n : ℕ) (ω : Ω) : ℝ :=
  max (-C / (1 - m))
    (min ((empMean X n ω - m) / (empVar X n ω + (empMean X n ω - m) ^ 2)) (C / m))

end Learning.Betting
end

-- ═══ Wang2026Almost.Mathlib.Probability.AsymptoticsInProbability ═══
@[expose] public section
open Filter MeasureTheory Asymptotics
open scoped Topology
namespace ProbabilityTheory
variable {Ω : Type*} {mΩ : MeasurableSpace Ω} (P : Measure Ω)

/-- `X n = Ω_p(a n)`: for every `ε > 0` there is `δ > 0` such that `P(|X n| ≥ δ a n) ≥ 1 - ε`
for all but finitely many `n`. -/
def IsBigOmegaInProb (X : ℕ → Ω → ℝ) (a : ℕ → ℝ) : Prop :=
  ∀ ε : ℝ, 0 < ε → ∃ δ : ℝ, 0 < δ ∧ ∀ᶠ n in atTop, 1 - ε ≤ P.real {ω | δ * a n ≤ |X n ω|}

end ProbabilityTheory
end

-- ═══ Wang2026Almost.WAR2026.Proposition2_7 ═══
@[expose] public section
open MeasureTheory ProbabilityTheory Filter Learning Learning.Betting Real
open scoped Topology ProbabilityTheory
namespace Wang2026Almost
variable {Ω : Type*} {mΩ : MeasurableSpace Ω} {P' : Measure Ω} [IsProbabilityMeasure P'] {P : Measure ℝ} [IsProbabilityMeasure P] {m : ℝ}

/-- **Proposition 2.7** (Wang, Agrawal, Ramdas 2026): for i.i.d. observations `X` of law `P` on
`[0, 1]` with mean `m` and variance `σ² > 0`, the aGRAPA bet fractions with clipping constant
`C ∈ (0, 1)` satisfy `√n lam n → N(0, σ⁻²)` in distribution, hence `lam n = Ω_p(n^{-1/2})`, and
the aGRAPA wealth process converges to `0` almost surely. -/
theorem agrapa_bankrupt (hP : ∀ᵐ x ∂P, x ∈ Set.Icc (0 : ℝ) 1) (hm : ∫ x, x ∂P = m)
    (hvar : 0 < Var[id; P]) {C : ℝ} (hC : C ∈ Set.Ioo 0 1) {X : ℕ → Ω → ℝ}
    (hX : ∀ n, Measurable (X n))
    (hindep : iIndepFun X P') (hlaw : ∀ n, HasLaw (X n) P P') :
    TendstoInDistribution (fun (n : ℕ) ω ↦ √n * agrapaFraction C m X n ω) atTop (id : ℝ → ℝ)
        (fun _ ↦ P') (gaussianReal 0 ((Var[id; P])⁻¹).toNNReal) ∧
      IsBigOmegaInProb P' (agrapaFraction C m X) (fun n ↦ (n : ℝ) ^ (-1 / 2 : ℝ)) ∧
      ∀ᵐ ω ∂P', Tendsto (fun n ↦ wealth m (agrapaFraction C m X) X n ω) atTop (𝓝 0) := sorry

end Wang2026Almost
end
