module

public import Mathlib.Analysis.SpecialFunctions.Log.Basic
public import Mathlib.MeasureTheory.Integral.Bochner.Basic
public import Mathlib.Probability.IdentDistrib
public import Mathlib.Probability.Independence.InfinitePi
public import Mathlib.Probability.Kernel.Basic
public import Mathlib.Probability.Kernel.IonescuTulcea.Traj
public import Mathlib.Probability.Process.FiniteDimensionalLaws
public import Mathlib.Probability.HasCondDistrib
public import Mathlib.MeasureTheory.Measure.ProbabilityMeasure
public import Mathlib.Probability.Independence.Basic
public import Mathlib.Probability.Independence.Conditional
public import Mathlib.MeasureTheory.Measure.SubFinite
public import Mathlib.Probability.Kernel.RadonNikodym
public import Mathlib.MeasureTheory.MeasurableSpace.Embedding
public import Mathlib.Order.Restriction
public import Mathlib.Probability.Kernel.IonescuTulcea.Maps
public import Mathlib.Analysis.Normed.Ring.Basic
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Basic
public import Mathlib.Probability.Kernel.Composition.MapComap
public import Mathlib.Probability.Moments.Basic
public import Mathlib.Probability.Distributions.Gamma
public import Mathlib.MeasureTheory.Function.ConvergenceInDistribution
public import Mathlib.MeasureTheory.Measure.Dirac.Basic
public import Mathlib.MeasureTheory.Measure.Dirac.Def
public import Mathlib.Probability.HasLaw

/-! # Standalone extraction for `Wang2026Almost.tendstoInDistribution_hindsightLogWealth`
Definitions are copied verbatim; theorem proofs are replaced by `sorry`.
Auto-generated by ChallengeGen. -/

set_option quotPrecheck false

-- The options the project is built with.
set_option autoImplicit false
set_option relaxedAutoImplicit false

-- Namespace stubs (so later `open`s resolve).
namespace MeasureTheory
end MeasureTheory
namespace Learning.Betting
end Learning.Betting
namespace ProbabilityTheory
end ProbabilityTheory
namespace Learning
end Learning
namespace Wang2026Almost
end Wang2026Almost

-- ═══ Wang2026Almost.LeanMachineLearning.Betting.Wealth ═══
@[expose] public section
open MeasureTheory Finset
namespace Learning.Betting
variable {Ω : Type*}

/-- The range `[-1 / (1 - m), 1 / m]` of the bet fractions for which the wealth stays
nonnegative when the observations are in `[0, 1]`. -/
def fractionRange (m : ℝ) : Set ℝ := Set.Icc (-1 / (1 - m)) (1 / m)

/-- The wealth after `n` rounds of the predictable plug-in betting strategy `lam` on the
observations `X`, testing the null mean `m`: `∏_{k < n} (1 + lam k (X k - m))`. -/
noncomputable def wealth (m : ℝ) (lam X : ℕ → Ω → ℝ) (n : ℕ) (ω : Ω) : ℝ :=
  ∏ k ∈ range n, (1 + lam k ω * (X k ω - m))

/-- The wealth of the fixed-fraction strategy betting the fraction `l` at every round. -/
noncomputable def fixedWealth (m l : ℝ) (X : ℕ → Ω → ℝ) : ℕ → Ω → ℝ := wealth m (fun _ _ ↦ l) X

/-- The best-in-hindsight log-wealth after `n` rounds:
`log (sup_{l ∈ fractionRange m} fixedWealth m l X n)`. -/
noncomputable def hindsightLogWealth (m : ℝ) (X : ℕ → Ω → ℝ) (n : ℕ) (ω : Ω) : ℝ :=
  Real.log (⨆ l : fractionRange m, fixedWealth m (l : ℝ) X n ω)

end Learning.Betting
end

-- ═══ Wang2026Almost.Mathlib.Probability.Distributions.ChiSquare ═══
@[expose] public section
open MeasureTheory Real Set
open scoped ENNReal
namespace ProbabilityTheory
section PDF
variable {k : ℕ} {x : ℝ}

/-- The pdf of the chi-squared distribution with `k` degrees of freedom. -/
noncomputable def chiSquarePDFReal (k : ℕ) (x : ℝ) : ℝ := gammaPDFReal (k / 2) (1 / 2) x

end PDF

/-- The chi-squared distribution with `k` degrees of freedom: the gamma distribution with shape
`k / 2` and rate `1 / 2`. -/
noncomputable def chiSquareMeasure (k : ℕ) : Measure ℝ := gammaMeasure ((k : ℝ) / 2) (1 / 2)

/-- The chi-squared distribution with `k ≠ 0` degrees of freedom is a probability measure. -/
lemma isProbabilityMeasure_chiSquareMeasure {k : ℕ} (hk : k ≠ 0) :
    IsProbabilityMeasure (chiSquareMeasure k) := sorry

instance instIsProbabilityMeasureRealChiSquareMeasureOfNeZeroNat (k : ℕ) [NeZero k] : IsProbabilityMeasure (chiSquareMeasure k) :=
  isProbabilityMeasure_chiSquareMeasure (NeZero.ne k)

end ProbabilityTheory
end

-- ═══ Wang2026Almost.WAR2026.Theorem5_1 ═══
@[expose] public section
open MeasureTheory ProbabilityTheory Filter Learning Learning.Betting
open scoped Topology
namespace Wang2026Almost
variable {Ω : Type*} {mΩ : MeasurableSpace Ω} {P' : Measure Ω} [IsProbabilityMeasure P'] {P : Measure ℝ} [IsProbabilityMeasure P] {m : ℝ}

/-- **Theorem 5.1, `χ²` limit** (Wang, Agrawal, Ramdas 2026): for i.i.d. observations `X` of a
non-degenerate law `P` on `[0, 1]` with mean `m`, twice the best-in-hindsight log-wealth
`2 L*_n = 2 max_{l ∈ [-1/(1-m), 1/m]} log W_n^l` converges in distribution to the `χ²`
distribution with one degree of freedom. -/
theorem tendstoInDistribution_hindsightLogWealth (hP : ∀ᵐ x ∂P, x ∈ Set.Icc (0 : ℝ) 1)
    (hm : ∫ x, x ∂P = m) (hnd : P ≠ Measure.dirac m) {X : ℕ → Ω → ℝ} (hX : ∀ n, Measurable (X n))
    (hindep : iIndepFun X P')
    (hlaw : ∀ n, HasLaw (X n) P P') :
    TendstoInDistribution (fun (n : ℕ) ω ↦ 2 * hindsightLogWealth m X n ω) atTop (id : ℝ → ℝ)
      (fun _ ↦ P') (chiSquareMeasure 1) := sorry

end Wang2026Almost
end
