/-
Copyright (c) 2026 Rémy Degenne. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Rémy Degenne
-/
module

public import Wang2026Almost.LeanMachineLearning.SequentialLearning.ObliviousEnv

/-!
# Runs in the i.i.d. environment and the filtration of the actions

In a run `(A, Y)` of an algorithm in the i.i.d. environment `Environment.const μ`, the feedback
`Y n` is independent of LML's filtration `IsAlgEnvSeq.filtrationAction` at time `n` (generated by
the history of the first `n` rounds, the observation and the action of round `n`). Together with
LML's `IsAlgEnvSeq.adapted_action_filtrationAction` and
`IsAlgEnvSeq.measurable_feedback_filtrationAction_of_lt`, this says that the feedbacks are
i.i.d. along `filtrationAction`, to which the actions are adapted: the actions are predictable
for a filtration along which the feedbacks are i.i.d. with law `μ`.

## Main statements

* `IsAlgEnvSeq.indep_feedback_filtrationAction_const`: `Y n` is independent of
  `h.filtrationAction n`.
* `IsAlgEnvSeq.measurable_feedback_filtrationAction_succ`: `Y n` is
  `h.filtrationAction (n + 1)`-measurable.
-/

@[expose] public section

open MeasureTheory ProbabilityTheory

namespace Learning.IsAlgEnvSeq

variable {Ω 𝓞 𝓐 𝓨 : Type*} [MeasurableSpace 𝓞] [MeasurableSpace 𝓐] [MeasurableSpace 𝓨]
  {mΩ : MeasurableSpace Ω} {P : Measure Ω} [IsProbabilityMeasure P]

/-- The feedback of round `n` is measurable for the filtration of the actions at time `n + 1`. -/
lemma measurable_feedback_filtrationAction_succ {alg : Algorithm 𝓞 𝓐 𝓨}
    {env : Environment 𝓞 𝓐 𝓨} {O : ℕ → Ω → 𝓞} {A : ℕ → Ω → 𝓐} {Y : ℕ → Ω → 𝓨}
    (h : IsAlgEnvSeq O A Y alg env P) (n : ℕ) :
    Measurable[h.filtrationAction (n + 1)] (Y n) :=
  h.measurable_feedback_filtrationAction_of_lt n.lt_succ_self

/-- In a run against `Environment.const μ`, the feedback of round `n` is independent of the
filtration of the actions at time `n` (the past rounds, the observation and the action of round
`n`). -/
lemma indep_feedback_filtrationAction_const {alg : Algorithm Unit 𝓐 𝓨} {O : ℕ → Ω → Unit}
    {A : ℕ → Ω → 𝓐} {Y : ℕ → Ω → 𝓨} {μ : Measure 𝓨} [IsProbabilityMeasure μ]
    (h : IsAlgEnvSeq O A Y alg (Environment.const μ) P) (n : ℕ) :
    Indep (MeasurableSpace.comap (Y n) inferInstance) (h.filtrationAction n) P := by
  have h' := (h.indepFun_feedback_const n).symm
  rw [IndepFun_iff_Indep] at h'
  rwa [h.filtrationAction_eq_comap]

end Learning.IsAlgEnvSeq
